CREATE TABLE `CUSTOMER`
(
    `ID` INT(11) NOT NULL,
    `LAST_NAME` VARCHAR(50) NULL DEFAULT NULL,
	`FIRST_NAME` VARCHAR(50) NULL DEFAULT NULL,
    `ADDRESS` VARCHAR(255) NULL DEFAULT NULL,
	 PRIMARY KEY (`id`)
);

CREATE TABLE `PURCHASE`
(
    `ID` INT(11) NOT NULL,
    `CUSTOMER_ID` INT(11) NOT NULL,
    `ORDER_TOTAL` NUMERIC(20, 2),
    `ORDER_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	 PRIMARY KEY (`id`)
);
